/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('@arco-design/web-vue')['Avatar']
    AButton: typeof import('@arco-design/web-vue')['Button']
    AComment: typeof import('@arco-design/web-vue')['Comment']
    AEmpty: typeof import('@arco-design/web-vue')['Empty']
    AForm: typeof import('@arco-design/web-vue')['Form']
    AFormItem: typeof import('@arco-design/web-vue')['FormItem']
    AInput: typeof import('@arco-design/web-vue')['Input']
    AInputSearch: typeof import('@arco-design/web-vue')['InputSearch']
    AMenu: typeof import('@arco-design/web-vue')['Menu']
    AMenuItem: typeof import('@arco-design/web-vue')['MenuItem']
    AModal: typeof import('@arco-design/web-vue')['Modal']
    APagination: typeof import('@arco-design/web-vue')['Pagination']
    AScrollbar: typeof import('@arco-design/web-vue')['Scrollbar']
    ASpace: typeof import('@arco-design/web-vue')['Space']
    ATabPane: typeof import('@arco-design/web-vue')['TabPane']
    ATabs: typeof import('@arco-design/web-vue')['Tabs']
    CookieDialog: typeof import('./src/components/dialogs/login/CookieDialog.vue')['default']
    DialogTemplate: typeof import('./src/components/dialogs/DialogTemplate.vue')['default']
    Layout: typeof import('./src/components/Layout.vue')['default']
    QrcodeLoginDialog: typeof import('./src/components/dialogs/login/QrcodeLoginDialog.vue')['default']
    QrcodeLoginDialogBak: typeof import('./src/components/dialogs/login/QrcodeLoginDialogBak.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
